# Generated by Django 4.1.2 on 2022-10-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filed1', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FancyLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleText', models.CharField(max_length=200)),
                ('contentText', models.CharField(max_length=200)),
                ('url', models.URLField(verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='HeadWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleText', models.CharField(max_length=50)),
            ],
        ),
    ]
