name: DjangoKey

on:
  push:
      branches:
        - master
jobs:
 build:
 
    runs-on: ubuntu-latest
    
    steps:
    - name: create-json
      run: |
        echo "${{ secrets.SECRET_KEY }}" > .env
        
