name: DjangoKey

on:
  push:
      branches:
        - master
jobs:
 build:
 
    runs-on: ubuntu-latest
    
    steps:
    - name: create-json
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: echo $SECRET_KEY
        
