name: DjangoKey

on:
  push:
      branches:
        - master
jobs:
 build:
 
    runs-on: ubuntu-latest
    
    steps:
    - name: create-env-json
      uses: schdck/create-env-json@v2
      id: create-env
      with:
        file-name: 'SECRET_KEY.json'
        SECRET_KEY: ${{ secret.SECRET_KEY }}
